bot_token: MTIwMjI1MDYwODY0MDI2MjIxNA.G8TOX8.flJc63Ek5pwBT9Noiv9ZuW33N90Y4--eW36Be0
weather_api_key: 62be20575b6b4106a5072104240102
weather_api_url: http://api.weatherapi.com/v1
weather_api_current: current.json
google_translate_api_key: AIzaSyDIuo_r0JAwY6bvOwjWXpIpBJjlrIoxBU4